# Credits: https://urre.me/writings/docker-compose-and-jekyll/.
version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: bundle exec jekyll serve --livereload --host 0.0.0.0
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
